[build]
base = "src"
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.47.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.47.1"